### ISSUE TITLE
largevis command line error

### ISSUE THREAD

**Issue by PJthunder** [DeepGraphLearning/graphvite#14]
I just have a try of the command line for the Large viz. But the command `graphvite visualize filename` actually returns an error:
"TypeError: load() takes 1 positional argument but 2 were given".
Is there something wrong with the arguments loading for the command line?

**Comment by KiddoZhu** [comment]
Thanks for pointing out this bug. You can modify [this line](https://github.com/DeepGraphLearning/graphvite/blob/cffa261d2e6b1ba59e83ebcdd9201898a64cd7b9/python/graphvite/cmd.py#L135) to

`app.load(vectors=vectors, perplexity=args.perplexity)`

It should work now.

**Comment by KiddoZhu** [comment]
Fixed. Will update it to conda.

**Comment by PJthunder** [comment]
Thanks for your efforts. Just update it through conda. Not sure whether there's is anything wrong or not with my environment setup. The same error still exists.

The graphvite version is still 0.1.0 on my side. Not sure whether it is updated on conda side already or not, since this [page](https://anaconda.org/milagraph/graphvite) shows the last modified on 08-08-2019.

**Comment by KiddoZhu** [comment]
Sorry I have some trouble with conda compilation now. The repo is fixed. You'd better manually modify that file. It could be found in `lib/python*.*/site-packages/graphvite/cmd.py`.

**Comment by PJthunder** [comment]
No problem. Just edit that locally. It looks working now.

**Comment by KiddoZhu** [comment]
Updated to conda.
